pipeline:
  sftp_cache:
    restore: true
    mount: /drone/.stack

  build:
    image: kyleondy/hakyll-build:latest
    pull: true
    commands:
      - mkdir -p /drone/.stack
      - cp -a /drone/.stack /root
      - rm -rf /drone/.stack
      - make build
      - make check
      - cp -a /root/.stack /drone

  sftp_cache:
    rebuild: true
    mount: /drone/.stack
