pipeline:
  sftp_cache:
    restore: true
    pull: true
    mount: /drone/.stack

  build:
    image: fpco/stack-build:lts
    pull: true
    commands:
      - mkdir -p /drone/.stack
      - cp -a /drone/.stack /root
      - rm -rf /drone/.stack
      - make package
      - cp -a /root/.stack /drone

  sftp_cache:
    rebuild: true
    mount: /drone/.stack

  deploy-staging:
    when:
      branch: staging
    image: kyleondy/alpine-rsync:stable
    pull: true
    commands:
      - ./deploy.sh staging

  deploy-production:
    when:
      branch: master
    image: kyleondy/alpine-rsync:stable
    pull: true
    commands:
      - ./deploy.sh production
