build:
  image: fpco/stack-build
  commands:
    - mkdir -p /drone/.stack
    - cp -av /drone/.stack /root
    - make build
    - make check
    - cp -av /root/.stack /drone

cache:
  mount:
    - /drone/stack
