pipeline:

  sftp_cache:
    mount: .stack/
    restore: true

  build:
    image: fpco/stack-build
    commands:
      - mkdir -p /root/.stack .stack
      - touch .stack/HomeDirTouch
      - touch /root/.stack/rootDirTouch
      # stack stores it's cache in /root. We can only cache our $HOME with drone.
      # Move $HOME/.stack to /root/.stack
      - cp -av .stack /root/
      - make build
      - make check
      - cp -av /root/.stack .

  sftp_cache:
    mount: .stack/
    rebuild: true
