pipeline:
  sftp_cache:
    restore: true
    mount: /drone/.stack

  build:
    image: fpco/stack-build:lts
    pull: true
    commands:
      - [[ -e /drone/.stack ]] && cp -a /drone/.stack /root
      - rm -rf /drone/.stack
      - make build
      - make check
      - cp -a /root/.stack /drone

  sftp_cache:
    rebuild: true
    mount: /drone/.stack
