pipeline:
  sftp_cache:
    restore: true
    mount: /cache/drone/.stack

  build:
    image: fpco/stack-build:lts
    pull: true
    commands:
      - mkdir -p /drone/.stack
      - cp -av /drone/.stack /root
      - rm -rf /drone/.stack
      - make build
      - make check
      - cp -av /root/.stack /drone

  sftp_cache:
    rebuild: true
    mount: /cache/drone/.stack
