rules:
  protection:
    required_status_checks:
      contexts:
        - continuous-integration/travis-ci
    required_pull_request_reviews:
      required_approving_review_count: 1
  branches:
    protection:
      auto-deployment:
        required_pull_request_reviews: null
