# Use new container infrastructure to enable caching
sudo: false

language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack


# GHC depends on GMP. You can add other dependencies here as well.
addons:
  apt:
    packages:
    - libgmp-dev


matrix:
  include:
  - env: BUILD=stack ARGS="--resolver lts-8"
    compiler: ": #stack default"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--resolver lts"
    compiler: ": #stack default"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--resolver nightly"
    compiler: ": #stack default"
    addons: {apt: {packages: [libgmp-dev]}}

  allow_failures:
  # lts-7 since hakyll can't buld in lts7
  - env: BUILD=stack ARGS="--resolver lts"
  - env: BUILD=stack ARGS="--resolver nightly"

before_install:
- unset cc
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- make STACK_ARGS="$ARGS" build

#script: make STACK_ARGS="$ARGS" check
deploy:
    provider: script
    script: gem install s3_website && s3_website push
    skip_cleanup: true
    on:
      branch: master
